version: '3'

services:
  bot:
    build: .
    restart: always
    env_file: env/prod.env
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:alpine
    env_file: env/prod.env
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    env_file: env/prod.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: